### ISSUE TITLE
Request for Clarity on the Future for Reload4J

### ISSUE THREAD

**Issue by geoffblandrbs** [qos-ch/reload4j#18]
Thanks all for work in hardening this. I've been testing reload4j and it's very nice that it is a simple drop-in replacement - it works great. 

I note your statement that this is meant _"to fix most pressing security issues. It is intended as a drop-in replacement for log4j version 1.2.17_". I also read the comments about the Apache Software Foundation still considering log4j v1 as end of life. But I do note that SLF4J is now also supporting reload4J. 

With the recent log4jv2 issues the spot-light has been placed on all logging systems and our security team are not happy that slf4j v1 is end of life. If we go to the security team and recommend replacing our existing log4jv1 JARs with reload4j I know what they will ask next. 

Whilst I realise that, like most open-source, you probably do this in your spare time, would it be possible to clarify on the reload4j web site future plans. Is this still end-of-life, just a one shot replacement for log4jv1? Or will it now be a maintained (if needed) fork going forward - so no-longer end of life?

I do realise this is "how long is a piece of string" question but just some clarity on the website would be very useful.

**Comment by ceki** [comment]
I expect reload4j to be maintained for the foreseeable future.

**Comment by ceki** [comment]
added a few words on the matter at https://reload4j.qos.ch

**Comment by geoffblandrbs** [comment]
> added a few words on the matter at https://reload4j.qos.ch

Exactly what we needed - thanks!
