### ISSUE TITLE
Localization issues in tests

### ISSUE THREAD

**Issue by fipro78** [qos-ch/reload4j#38]
When I try to execute the build locally I get the following error:

    [ERROR] Failures:
    [ERROR]   TestLogMF.testDebugDouble:458 expected:<Iteration 3[,]142> but was:<Iteration 3[.]142>
    [ERROR]   TestLogMF.testDebugFloat:446 expected:<Iteration 3[,]142> but was:<Iteration 3[.]142>
    [ERROR]   TestLogMF.testInfoDouble:702 expected:<Iteration 3[,]142> but was:<Iteration 3[.]142>
    [ERROR]   TestLogMF.testInfoFloat:690 expected:<Iteration 3[,]142> but was:<Iteration 3[.]142>
    [ERROR]   TestLogMF.testTraceDouble:249 expected:<Iteration 3[,]14> but was:<Iteration 3[.]14>
    [ERROR]   TestLogMF.testTraceFloat:235 expected:<Iteration 3[,]14> but was:<Iteration 3[.]14>

I suppose this is a localization issue in the test case.

**Comment by fipro78** [comment]
I executed the build with -DskipTests=true

Just tried again after pulling the latest changes and the issue still occurs.

IMHO the issue is that the test uses `NumberFormat.getInstance();` without a `Locale` parameter. So it uses the current default locale. Not sure if the trace() method takes the Locale into account. But there seems to be a mismatch on my machine.

**Comment by ceki** [comment]
I see. Hopefully fixed in new commit ad82fa07bc40b

**Comment by fipro78** [comment]
@ceki Unfortunately not. But actually it is not an issue in the code, it is an issue in the tests. The tests are not using the same format with `Locale` as the code, so they do not match.

I got it working locally now and will prepare a PR.

**Comment by fipro78** [comment]
@ceki I also thought that your change was not necessary and should be reverted to ensure that no side effect happens. But I didn't want to change it without your oppinion. :)

Just pulled the latest master and successfully executed the build. Tests are all passing now.
