### ISSUE TITLE
Improve appender looping performance in Category

### ISSUE THREAD

**Issue by ceki** [qos-ch/reload4j#46]
Replace Vector with a better implementation for lopping on appenders

**Comment by OlivierJaquemet** [comment]
Hi @ceki 

As I understand, you fixed this issue in the 1.2.20 with this commit :
https://github.com/qos-ch/reload4j/commit/63ff036d11b14767365197a79606cb6df6102c3a

I think this issue can be closed ?

**Comment by ceki** [comment]
Yes, thank you.
