### ISSUE TITLE
create a tag for the 1.2.18.0 version in git

### ISSUE THREAD

**Issue by ceki** [qos-ch/reload4j#7]
Hannes Rosenögger on 2022-01-13: 
Currently, there is no way for people to know from which commit the 1.2.18.0 version has been created.
I think it's important for people to be able to reproduce a build if they need to.

**Comment by ceki** [comment]
@123haynes Done.

**Comment by 123Haynes** [comment]
@ceki awesome :) Thanks for this 👍
