### ISSUE TITLE
MDC setContextMap is not working correctly

### ISSUE THREAD

**Issue by jivedude** [qos-ch/reload4j#74]
The reload4j setContextMap relies on the MDC.getContext() call to get the current MDC map, and then does a putAll on the provided Map to override or set new values. 

However the getContext() call does a new HashTable() , so it returns a copy of the Map thats stored in the ThreadLocal. So when putting in new key/values it does this in the copy and not in the stored ThreadLocal. Thus loosing the new MDC map on the next getContext Call. 

    public static Hashtable<String, Object> getContext() {
        return new Hashtable((Map)localMap.get());
    }

**Comment by ceki** [comment]
@jivedude Which `setContextMap` method are you referring to? There is no `setContextMap` method in `org.apache.log4j.MDC`

**Comment by jivedude** [comment]
My bad i think i have the wrong project. 
It's in slf4-reload4j which my native search brought me to the wrong github.
