### ISSUE TITLE
Date problem on the website

### ISSUE THREAD

**Issue by Neustradamus** [qos-ch/reload4j#8]
Dear @qos-ch team, @ceki,

In first, I wish you a Happy New Year 2022!

ATTENTION: Date problem on the website: "30th of August, 2021 - Release of SLF4J 1.7.33"

Maybe good to change all dates by YYYY-MM-DD.

Here: https://www.slf4j.org/news.html

**Comment by Neustradamus** [comment]
@ceki: Thanks too :)

No here: https://www.slf4j.org/news.html

**Comment by ceki** [comment]
OK. Fixed. Thank you.

**Comment by Neustradamus** [comment]
@ceki: Thanks!

Can you replace all previous date by YYYY-MM-DD?

**Comment by ceki** [comment]
That would be quite an ungrateful task. Does it make a difference in any way?

**Comment by Neustradamus** [comment]
Harmonization and better...

**Comment by 123Haynes** [comment]
I think it's a personal preference.  
If harmonization is your goal it would be much easier to adjust just the last 2 news entries date format to be the same as all previous entries.   
But in the end it doesn't really matter imho 😃

**Comment by Neustradamus** [comment]
You can add the different websites on GitHub, easy to contribute :)
